# Generated by Django 5.1 on 2024-09-02 17:03 - Aca tenemos todo el codigo que va a utilizar django para crear la tabla en la DB

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_created', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
